[build]
  publish = "dist"
  command = "npm install && npm run build"
  functions = "netlify/functions"
  # Only include necessary files for frontend build
  ignore = "backend/,tests/,docs/,*.md,.env*,*.sql"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "8"
  NODE_ENV = "production"
  # Frontend build environment variables only
  VITE_SUPABASE_URL = "https://xoivxzjhgjyvuzcmzcas.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvaXZ4empoZ2p5dnV6Y216Y2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTQ1NjgsImV4cCI6MjA2NzgzMDU2OH0.ny0Gnf6uVbk9nrLq6VTYqjf9KPVSt2KczF223hf8ZZg"
  # Configure secrets scanning to exclude certain paths and keys
  SECRETS_SCAN_OMIT_PATHS = "backend/,dist/,dev-dist/,tests/,docs/,*.md,.env*,*.sql"
  SECRETS_SCAN_OMIT_KEYS = "PORT,NODE_ENV,SUPABASE_JWT_SECRET,FRONTEND_URL,BACKEND_URL,SMTP_PASS,SMTP_USER,SMTP_HOST"

# Production context
[context.production]
  command = "npm install && npm run build"
  
[context.production.environment]
  NODE_ENV = "production"
  VITE_DEPLOY_CONTEXT = "production"

# Deploy preview context (for pull requests)
[context.deploy-preview]
  command = "npm install && npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "staging"
  VITE_DEPLOY_CONTEXT = "deploy-preview"

# Branch deploy context (for feature branches)
[context.branch-deploy]
  command = "npm install && npm run build"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_DEPLOY_CONTEXT = "branch-deploy"

# Plugin to auto-install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Function environment variables (runtime, not build-time)
# These are available to your Netlify Functions but NOT during the frontend build
# This prevents "exposed secrets" warnings while keeping your API functional
[functions.environment]
  # Supabase
  SUPABASE_URL = "https://xoivxzjhgjyvuzcmzcas.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvaXZ4empoZ2p5dnV6Y216Y2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTQ1NjgsImV4cCI6MjA2NzgzMDU2OH0.ny0Gnf6uVbk9nrLq6VTYqjf9KPVSt2KczF223hf8ZZg"
  
  # URLs
  FRONTEND_URL = "https://diginum.netlify.app"
  BACKEND_URL = "https://diginum.netlify.app"
  
  # Other
  PORT = "8888"
  TEST_MODE = "true"
  NODE_ENV = "production"

# API redirects to Netlify Functions (must come first)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Exchange rates endpoint redirect
[[redirects]]
  from = "/exchange-rates"
  to = "/.netlify/functions/api/exchange-rates"
  status = 200

# Exchange rates update function redirect
[[redirects]]
  from = "/update-exchange-rates"
  to = "/.netlify/functions/update-exchange-rates"
  status = 200

# Swychr webhook redirect
[[redirects]]
  from = "/webhooks/swychr"
  to = "/.netlify/functions/swychr-webhook"
  status = 200

# Redirect all other requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.exchangerate-api.com https://ipapi.co https://fonts.googleapis.com https://fonts.gstatic.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"