[build]
  publish = "dist"
  command = "npm run build && cd netlify/functions && npm install"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  NODE_ENV = "production"

# Production context
[context.production]
  command = "npm run build && cd netlify/functions && npm install"
  
[context.production.environment]
  NODE_ENV = "production"
  VITE_DEPLOY_CONTEXT = "production"

# Deploy preview context (for pull requests)
[context.deploy-preview]
  command = "npm run build && cd netlify/functions && npm install"
  
[context.deploy-preview.environment]
  NODE_ENV = "staging"
  VITE_DEPLOY_CONTEXT = "deploy-preview"

# Branch deploy context (for feature branches)
[context.branch-deploy]
  command = "npm run build && cd netlify/functions && npm install"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_DEPLOY_CONTEXT = "branch-deploy"

# Plugin to auto-install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# API redirects to Netlify Functions (must come first)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all other requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://*.supabase.co wss://*.supabase.co https://api.fapshi.com https://api.exchangerate-api.com https://ipapi.co https://fonts.googleapis.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"